### ISSUE TITLE
Workload identity is not available as authorization method

### ISSUE THREAD

**Issue by rbrondgeest** [prometheus-community/stackdriver_exporter#135]
When stackdriver exporter is used inside a GKE cluster that authorizes workloads using "workload identity" the stackdriver_exporter does not show any stackdriver metrics.

https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity

Im using Stackdriver exporter in a pod with properly authorized & authenticated service account, that has been coupled to a google cloud service account using "workload identity". 
The pod was tested with other tools such as gcloud, and ive confirmed that the monitoring API can be called from within the pod.

**Comment by hinricht** [comment]
I can confirm it's working as expected.
Using a GCP serviceaccount assigned to the `roles/monitoring.viewer` IAM role scrape the right metrics for us.

**Comment by filip-aipl** [comment]
Wanted to confirm, as of now, it works with Workload Identity
