### ISSUE TITLE
New Version Release

### ISSUE THREAD

**Issue by netzere** [prometheus-community/stackdriver_exporter#301]
Hi, 

There are some new features we'd like to use (for example: https://github.com/prometheus-community/stackdriver_exporter/pull/243) and i see there is no a new release since May 2023.

Is there any plan to release a new version?

Thanks!

**Comment by netzere** [comment]
Hi @SuperQ, is it possible to cut a new release soon?

**Comment by SuperQ** [comment]
https://github.com/prometheus-community/stackdriver_exporter/releases/tag/v0.15.0
