### ISSUE TITLE
bigquery metrics are not working

### ISSUE THREAD

**Issue by agusl88** [prometheus-community/stackdriver_exporter#33]
Seems like metrics from bigquery are not working, no related metrics are available on prometheus and the **stackdriver_exporter** executable file is not throwing any errors or warnings.

The metrics i'm trying are the following:

> bigquery.googleapis.com/query/count,bigquery.googleapis.com/query/execution_times,bigquery.googleapis.com/query/scanned_bytes_billed,bigquery.googleapis.com/storage/uploaded_bytes_billed

**Comment by fastest963** [comment]
The issue is that BigQuery metrics are behind significantly from real-time. Support has indicated to us that they're working to bring the metrics to a more real-time state but I haven't heard anything about it in months.

**Comment by agusl88** [comment]
thanks, it makes sense. Lets continue the discussion in the other issue
