### ISSUE TITLE
[Feature request] Allow metrics-type-prefixes using multiple flags

### ISSUE THREAD

**Issue by snebel29** [prometheus-community/stackdriver_exporter#44]
The flag `--monitoring.metrics-type-prefixes` can easily become a long string hard to read, in some file formats like when provided in a k8s yaml manifests within a list, indented, etc..  can be tricky to split the string without adding extra spaces, making readability hard.

I think it'd be nice to being able to provide prefixes repeating a flag, may be create an additional `--monitoring.metrics-type-prefix` flag (singular) that can be repeated and which values would be merged/combined with env var `STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES ` and prefixes flag (plural).

I'm happy to PR if that makes sense, thanks.

**Comment by SuperQ** [comment]
This mostly sounds like a configuration management problem. But I don't see an issue making `--monitoring.metrics-type-prefixes` be repeatable. There's no need to make separate flags for this.

I might suggest dropping the word `type` from the flag, as it's a bit "meta". `--monitoring.metrics-prefixes` makes more sense to me.
