### ISSUE TITLE
Multiple project ID support

### ISSUE THREAD

**Issue by lahsivjar** [prometheus-community/stackdriver_exporter#55]
I have a use case where I want to scrape data from multiple gcp projects. I was thinking of adding this support via a PR to take comma separated project ids and launch them in multiple goroutines. 

What do you guys think? Does it make sense to do this?

**Comment by ashiddo11** [comment]
This makes a lot of sense as I'm having the same issue and dont want to run multiple replicas of the exporter scraping different projects

**Comment by SuperQ** [comment]
Fixed with https://github.com/prometheus-community/stackdriver_exporter/pull/105
