### ISSUE TITLE
add timestamp on metrics

### ISSUE THREAD

**Issue by achilles42** [prometheus-community/stackdriver_exporter#58]
the current implementation of stackdriver_exporter doesn't add timestamp on metrics. if a timestamp is not added to metrics, Prometheus adds the scrape timestamp on the metrics scraped from /metrics endpoint on stackdriver_exporter. This implementation doesn't allow us to show the Stackdriver data collection [lag](https://cloud.google.com/monitoring/api/metrics_gcp) on the metrics(which we are storing on Prometheus) as Prometheus is adding the timestamp of scrape time.

[prometheus/client_golang](https://github.com/prometheus/client_golang) has feature released on  [v0.9](https://github.com/prometheus/client_golang/issues/187) version, which allows users to add timestamp on the metrics. 

We can use NewMetricWithTimestamp, which is a wrapper on top of existing metrics type which prometheus_client library provides.
```
prometheus.NewMetricWithTimestamp(
               reportTime,  // Get the timestamp from stackdriver metrics data
               prometheus.MustNewConstHistogram(
                       t.newMetricDesc(fqName, labelKeys),
                       uint64(dist.Count),
                       dist.Mean*float64(dist.Count),fake it
                       buckets,
                      labelValues...,
                ),
)
```

**Comment by achilles42** [comment]
Hey @frodenas, Please let me know if you have any feedback on the PR.

**Comment by SuperQ** [comment]
One word of warning when using timestamps on exported metrics, you can easily run into staleness problems which will create gaps in Prometheus. Or if the timestamp is too far off, Prometheus will drop the data entirely.

**Comment by SuperQ** [comment]
This is done.
