### ISSUE TITLE
Recover from expired/replaced credentials

### ISSUE THREAD

**Issue by cpick** [prometheus-community/stackdriver_exporter#66]
Thanks for writing such a useful tool!

In our environment, we use `vault` to create credentials for `stackdriver_exporter`.  Under certain error conditions those credentials expire and are replaced.  `stackdriver_exporter` then needs to be restarted to load the replacement.

We've currently maintain a [one-line fork](https://github.com/cpick/stackdriver_exporter/tree/fatal-collection-error) that accomplishes this by treating a failure to collect metrics [a fatal error](https://github.com/cpick/stackdriver_exporter/commit/c5c3b88bbaf1bc5978d2735833ef7cffe8ff16e9#diff-c2d48ff417505422031fabca2a3e1469R138).  This causes our process-manager to restart the service at which point it grabs the new credentials.

We'd love to get something that accomplished the same thing upstreamed.  What would you think about a merge request containing this (or a similar) change?

**Comment by SuperQ** [comment]
Seems like a good idea to me. The exporter currently exits the initial startup if the credentials don't work.

Right now that does a `log.Error()` and then `os.Exit(1)`. Maybe we should change that to a simple `log.Fatal()`.

Feel free to open a PR for this change.
