### ISSUE TITLE
Prometheus Community

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/stackdriver_exporter#72]
Is there any interest in bringing this exporter into the [Prometheus Community project](https://github.com/prometheus-community)?

**Comment by frodenas** [comment]
@SuperQ I've not been actively maintaining this repository, and in fact, I was thinking of archiving it. If there's a community out there that wants to maintain it, then I will be more than happy to transfer the ownership.

**Comment by SuperQ** [comment]
That would be awesome, there are a lot of GCP users that depend on this.

I will open an issue on the Prometheus Community side to get that going.

We can do this one of two ways, I can grant you an admin role in Prometheus Community, or you can grant me admin on this repo.

**Comment by SuperQ** [comment]
This has now been moved.
