### ISSUE TITLE
How to get instance_name in metrics from agent.googleapis.com/agent/*

### ISSUE THREAD

**Issue by tomsucho** [prometheus-community/stackdriver_exporter#78]
When I've added a metric like this one:
agent.googleapis.com/agent/memory_usage
into 
--monitoring.metrics-type-prefixes

I can see it gets the data however the resulting labels only contain instance_id and not instance_name.  
Googling around I found this page (https://github.com/grafana/grafana/issues/18750) in which they indicate it should be possible to get this:
"The Stackdriver Monitoring API supports grouping by metadata labels (system_labels, which include instance names, and user_labels, which are basically instance tags)"
Is this something stackdriver exporter can do as well? How to configure this?

**Comment by JoaoAlecrim** [comment]
Hello,

I'm having the same problem. Ideally it would be great to have also gcp metadata information as labels. Is it possible?

**Comment by tomsucho** [comment]
I figured a potential workaround based on the info from the docs: 
https://prometheus.io/docs/prometheus/latest/querying/operators/

`stackdriver_gce_instance_agent_googleapis_com_memory_percent_used{state="used"} *
on (instance_id) group_left(instance_name)
stackdriver_gce_instance_compute_googleapis_com_instance_uptime^0`

so we are joining two metrics on instance_id and then for every metric from the left(hence group_left used) we try to add a metric label  "instance_name" from the 2nd metric which is in this case instance uptime in the last 60sec interval. Now because this construct has to use some operator I decided to use * multiplication and so to not skew the metric value the 2nd metric has to be always 1 hence 2nd metric value needs ^0.
It does seem to work, what you think?

**Comment by JoaoAlecrim** [comment]
> I figured a potential workaround based on the info from the docs:
> https://prometheus.io/docs/prometheus/latest/querying/operators/
> 
> `stackdriver_gce_instance_agent_googleapis_com_memory_percent_used{state="used"} * on (instance_id) group_left(instance_name) stackdriver_gce_instance_compute_googleapis_com_instance_uptime^0`
> 
> so we are joining two metrics on instance_id and then for every metric from the left(hence group_left used) we try to add a metric label "instance_name" from the 2nd metric which is in this case instance uptime in the last 60sec interval. Now because this construct has to use some operator I decided to use * multiplication and so to not skew the metric value the 2nd metric has to be always 1 hence 2nd metric value needs ^0.
> It does seem to work, what you think?

It's similar to what I'm doing right now, don't have any other chance. Thanks for sharing, I could have done it also... 

This is what I'm doing to get CPU load > 10%:
sum by (instance_id,instance_name,project_id) (sum by (instance_id,project_id) (stackdriver_gce_instance_agent_googleapis_com_cpu_load_1_m) + on(instance_id) group_left(instance_name) sum by (instance_id,instance_name) (stackdriver_gce_instance_compute_googleapis_com_instance_network_received_bytes_count) * 0) / sum by (instance_id,instance_name,project_id)((stackdriver_gce_instance_compute_googleapis_com_instance_cpu_reserved_cores)) * 100 > 10

The auxiliary metric which contains the label I need is stackdriver_gce_instance_compute_googleapis_com_instance_network_received_bytes_count, which is being gathered by a stackdriver_exporter process as well.

**Comment by ocervell** [comment]
@tomsucho sorry to revive this, but I have the same issue. I see there is a `__metadata_instance_name` label in the gce_sd_configs but it doesn't appear in Stackdriver: any way to enable this ?
