### ISSUE TITLE
README.md out of sync for docker image

### ISSUE THREAD

**Issue by fbaier-fn** [prometheus-community/stackdriver_exporter#80]
When following the instructions https://github.com/prometheus-community/stackdriver_exporter#docker I get:

```
$ docker run -p 9255:9255 prometheus-community/stackdriver-exporter
Unable to find image 'prometheus-community/stackdriver-exporter:latest' locally
docker: Error response from daemon: pull access denied for prometheus-community/stackdriver-exporter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Where does the docker image actually gets pushed to?

**Comment by SuperQ** [comment]
https://github.com/prometheus-community/stackdriver_exporter/pull/79 should fix this up.

I think we'll need to cut a release in order to release a `latest` tag.

**Comment by fbaier-fn** [comment]
> #79 should fix this up.
> 
> I think we'll need to cut a release in order to release a `latest` tag.

Ah, it never got pushed I guess? Or tried to the "wrong" (non existing) org and thats why right now I cant find `stackdriver-exporter` in `prometheuscommunity` ?
