### ISSUE TITLE
create docker image

### ISSUE THREAD

**Issue by lod** [prometheus-community/stackdriver_exporter#81]
The stackdriver_exporter image is not listed on https://hub.docker.com/u/prometheuscommunity

Using the docker run line in the README does not work, access denied

**Comment by SuperQ** [comment]
I'm in the process of cutting a new release that will provide the `latest` tag.

**Comment by SuperQ** [comment]
I've released 0.7.0. This should now be fixed.

**Comment by lod** [comment]
Fantastic, thanks for the quick response
