### ISSUE TITLE
Invalid timestamps

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/stackdriver_exporter#93]
https://github.com/prometheus-community/stackdriver_exporter/pull/84 introduced timestamps, this produces invalid data for some metrics.

```
stackdriver_tcp_lb_rule_loadbalancing_googleapis_com_l_3_external_rtt_latencies_count{...} 1 -62135596800000
```

**Comment by SuperQ** [comment]
cc @lahsivjar

**Comment by lahsivjar** [comment]
Ack, will investigate this today

**Comment by lahsivjar** [comment]
@SuperQ Created PR for fixing it, #94
